### PR TITLE
Bugfix/ui update fixes

### PR DESCRIPTION
**Pull request by thekarel**
Allows Circle to build the JS bundle, also fixes a table view's styling

### CODE REVIEW

**Comment by clloyd** [comment]
I think these shouldn't be devDependencies, we're currently using the dev/non-dev dependencies to determine what needs to be installed by circle and what doesn't. If those new dependencies are required to build the project I'd argue that they're not devDependencies. We want the builds to be as fast as possible.

**Comment by thekarel** [comment]
I completely agree but that still wouldn't solve our problem with the CI server.

**Comment by clloyd** [comment]
:+1:

**Comment by clloyd** [comment]
@currysoup just noticed that repository being added, any reason for that?

**Comment by thekarel** [comment]
To suppress an npm warning.

**Comment by clloyd** [comment]
Ok, then we can use our actual repo address

**Comment by thekarel** [comment]
Oh, I see what you mean. My mistake, sorry!

**Pull request merged**
