### PR TITLE
Speedup the all tags XML route

### PR DESCRIPTION
**Pull request by hmgibson23**
This speeds up the XML all tabs route quite significantly. We should check it and see we also want to an export to S3 and just download that when it's requested but for now this seems like a pretty efficient way to grab all the tags.

I have also created a section cache since the tag sections needs to be exported in the XML

### CODE REVIEW

**Comment by clloyd** [comment]
Should this also listen to Section kinesis events like the tag cache does, to keep insync between instances?

**Comment by hmgibson23** [comment]
Yes it probably should!

**Comment by hmgibson23** [comment]
@clloyd - should be up to date now.

**Comment by clloyd** [comment]
:+1:

**Comment by clloyd** [comment]
@hmgibson23 This seems to be having issues on code?

**Comment by hmgibson23** [comment]
Will have a look

On 26 January 2016 at 17:20, Christopher Lloyd <notifications@github.com>
wrote:

> @hmgibson23 <https://github.com/hmgibson23> This seems to be having
> issues on code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/tagmanager/pull/87#issuecomment-175126341>.
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
