### PR TITLE
Podcasts: Add a field for Google Podcasts & Spotify Links

### PR DESCRIPTION
**Pull request by ajwl**
We want to send over Google Podcasts links and Spotify links, in addition to the iTunes url.

This updates the interface for Podcast series and the backend too.

### CODE REVIEW

**Comment by ajwl** [comment]
Branch deployed to CODE

**Comment by tomrf1** [comment]
👍 looks good, worth checking it gets into CODE capi

**Comment by ajwl** [comment]
@tomrf1 have added the changes
Is up now in CODE: https://tagmanager.code.dev-gutools.co.uk/tag/73818
Tho having trouble with local version of TM

**Comment by tomrf1** [comment]
@ajwl thanks, I'll test this with CODE capi and then we can merge

**Pull request merged**
