### PR TITLE
All XML routes in existing R2 index

### PR DESCRIPTION
**Pull request by hmgibson23**
This finalises all the routes in the current index. Still need to discuss the ones that currently 404 in code and see how they are used. 

The routes for fetching XML info about the tags are:
```
/tags/export/all
/tags/export/single/:id
/tags/export/merges/:since
```

### CODE REVIEW

**Comment by hmgibson23** [comment]
ping @clloyd

**Comment by clloyd** [comment]
@hmgibson23 do we pass that since in R2?, or do we need to track the last request time.

**Comment by hmgibson23** [comment]
No it gets passed in and I haven't implement those routes yet anyway (doing them now)

**Comment by clloyd** [comment]
:+1:

**Pull request merged**
