### PR TITLE
DO NOT MERGE BEFORE OR ON MONDAY ReadOnly endpoint Performance and Section Lookup Cache

### PR DESCRIPTION
**Pull request by currysoup**
Times gone from over 15 minutes down to about 20 seconds in initial testing.

### CODE REVIEW

**Comment by clloyd** [comment]
Can you mark this DO NO MERGE in title?

**Comment by currysoup** [comment]
Some approximate speedups:

| Endpoint | Speedup |
|--------------|--------------|
| /tags/export/all | x30 |
| /sections/export/all | x2 |
| /tools/newspaperintegration/created/0 | x3*|
| /tools/newspaperintegration/modified/0 | x7 |

* Rerunning this resulted in a speedup of about x30

**Comment by clloyd** [comment]
:+1:

**Comment by currysoup** [comment]
Seeing some weird behaviour with the kinesis stream clients not picking up data. Perhaps related to the execution contexts again. Investigating now...

**Comment by currysoup** [comment]
Just going to close this off. We currently scan the entire section DB into memory when performing read only options. This is plenty fast enough (since there are so few sections) and doesn't require us to handle cache coherency which is neat.

**Pull request closed without merging**
